parameters:
    # Organization
    volleyball.fixtures.organization: 2
    volleyball.fixtures.council: 4
    volleyball.fixtures.region: 8
    # Passel
    volleyball.fixtures.passel_type: 2
    volleyball.fixtures.passel: 16
    volleyball.fixtures.faction: 32
    volleyball.fixtures.leader: 32
    volleyball.fixtures.attendee_level: 4
    volleyball.fixtures.attendee_position: 4
    volleyball.fixtures.attendee: 64
    # Facility
    volleyball.fixtures.facility: 8
    volleyball.fixtures.department: 16
    volleyball.fixtures.quarters: 32
    volleyball.fixtures.quarters.passel: 16
    volleyball.fixtures.quarters.faculty: 16
    volleyball.fixtures.faculty: 16
    volleyball.fixtures.faculty_position: 16
    # Course
    volleyball.fixtures.course: 8
    volleyball.fixtures.requirement: 32
    volleyball.fixtures.class: 16
    # Enrollment
    volleyball.fixtures.season: 16
    volleyball.fixtures.week: 32
    volleyball.fixtures.period: 96
    volleyball.fixtures.facility_course: 32
    volleyball.fixtures.passel_enrollment: 32
    volleyball.fixtures.attendee_enrollment: 128
    # Utility
    volleyball.fixtures.address: 15
    volleyball.fixtures.carousel: 2
    volleyball.fixtures.carousel_item: 6
    # User
    volleyball.fixtures.user: 2
    # Report
    volleyball.fixtures.report: 1